version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run test

reports:
  jest-report:
    files:
      - 'packages/*/coverage/clover.xml'
    file-format: 'CLOVERXML'